[package]
name = "test-binary"
version = "0.1.0"
edition = "2024"

[dependencies]
bigtable_rs = "0.2.18"
reqwest = { version = "0.12", features = ["json", "hickory-dns"] }
tokio = { version = "1", features = ["full"] }
tracing-subscriber = "0.3"
tracing = "0.1"
